name: pyrite
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - huggingface_hub
  - wandb
  - timm
  - diffusers
  - accelerate
  - threadpoolctl
  - plotly
  - dill
  - einops
  - hydra-core
  - ipykernel
  - ipython
  - matplotlib
  - omegaconf
  - opencv
  - pandas
  - pyyaml
  - scipy
  - tqdm
  - zarr
  - spatialmath-python
  - numcodecs
  - scikit-video
  - scikit-fda
  - llvm-openmp=14
  - eigen=3.4
  - cmake
  - pybind11
  - boost
  - fmt
  - spdlog
  - pip
  - pip:
    - v4l2py
    - toppra
    - atomics
    - vit-pytorch
    - imagecodecs
    - cvxpy
